name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies and build
        env:
          REACT_APP_SERVER_DOMAIN_NAME: ${{ secrets.SERVER_DOMAIN }}
          EACT_APP_DEV_LOCAL_SERVER: ${{ secrets.LOCAL_SERVER }}
        run: |
          npm i
          npm run build

      - name: clear directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
          script: rm -rf /home/ubuntu/rewind-react/build/*

      - name: Copy Server files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/rewind-rewind/"

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/rewind-react
            git pull origin master
            npm install
            sudo service nginx restart
